// mock search response for testing to avoid exhausting Google API quota

export default {
  kind: "customsearch#search",
  url: {
    type: "application/json",
    template:
      "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
  },
  queries: {
    request: [
      {
        title: "Google Custom Search - testing",
        totalResults: "430000000",
        searchTerms: "testing",
        count: 10,
        startIndex: 1,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "9b3b6e249a0376ad8",
      },
    ],
    nextPage: [
      {
        title: "Google Custom Search - testing",
        totalResults: "430000000",
        searchTerms: "testing",
        count: 10,
        startIndex: 11,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "9b3b6e249a0376ad8",
      },
    ],
  },
  context: {
    title: "Google",
  },
  searchInformation: {
    searchTime: 0.616972,
    formattedSearchTime: "0.62",
    totalResults: "430000000",
    formattedTotalResults: "430,000,000",
  },
  items: [
    {
      kind: "customsearch#result",
      title: "Structured Data Testing Tool",
      htmlTitle: "Structured Data <b>Testing</b> Tool",
      link: "https://search.google.com/structured-data/testing-tool",
      displayLink: "search.google.com",
      snippet:
        "Main menu. Google apps. Structured Data Testing Tool. Structured Data Testing \nTool. Sign in. public. NEW TEST. settings. View Search Gallery; Help; Send ...",
      htmlSnippet:
        "Main menu. Google apps. Structured Data <b>Testing</b> Tool. Structured Data <b>Testing</b> <br>\nTool. Sign in. public. NEW <b>TEST</b>. settings. View Search Gallery; Help; Send&nbsp;...",
      cacheId: "eMgJEdTA-pMJ",
      formattedUrl: "https://search.google.com/structured-data/testing-tool",
      htmlFormattedUrl:
        "https://search.google.com/structured-data/<b>testing</b>-tool",
    },
    {
      kind: "customsearch#result",
      title: "PageSpeed Insights",
      htmlTitle: "PageSpeed Insights",
      link: "https://developers.google.com/speed/pagespeed/insights/",
      displayLink: "developers.google.com",
      snippet:
        "Make your web pages fast on all devices · What's New. Read the latest Google \nSearch Central blog posts about performance & speed. · Web Performance. \nLearn ...",
      htmlSnippet:
        "Make your web pages fast on all devices &middot; What&#39;s New. Read the latest Google <br>\nSearch Central blog posts about performance &amp; speed. &middot; Web Performance. <br>\nLearn&nbsp;...",
      cacheId: "dnJxySeYBCIJ",
      formattedUrl: "https://developers.google.com/speed/pagespeed/insights/",
      htmlFormattedUrl:
        "https://developers.google.com/speed/pagespeed/insights/",
      pagemap: {
        metatags: [
          {
            viewport: "initial-scale=1, width=device-width",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Rich Results Test - Google Search Console",
      htmlTitle: "Rich Results <b>Test</b> - Google Search Console",
      link: "https://search.google.com/test/rich-results",
      displayLink: "search.google.com",
      snippet:
        "What is this test? Test your publicly accessible page to see which rich results can \nbe generated by the structured data it contains.",
      htmlSnippet:
        "What is this <b>test</b>? <b>Test</b> your publicly accessible page to see which rich results can <br>\nbe generated by the structured data it contains.",
      cacheId: "48P8Ni8fA3EJ",
      formattedUrl: "https://search.google.com/test/rich-results",
      htmlFormattedUrl: "https://search.google.com/<b>test</b>/rich-results",
      pagemap: {
        metatags: [
          {
            "application-name": "Search Test Tool",
            referrer: "origin",
            "apple-mobile-web-app-status-bar-style": "black",
            "msapplication-tap-highlight": "no",
            viewport:
              "initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no",
            "apple-mobile-web-app-capable": "yes",
            "apple-mobile-web-app-title": "Search Test Tool",
            "mobile-web-app-capable": "yes",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Advanced Android in Kotlin 05.1: Testing Basics",
      htmlTitle: "Advanced Android in Kotlin 05.1: <b>Testing</b> Basics",
      link:
        "https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-basics/",
      displayLink: "codelabs.developers.google.com",
      snippet:
        "Feb 18, 2021 ... Learn the basics of testing your Android Kotlin apps. In this codelab you'll learn to \nrun tests, write basic tests, work with AndroidX Test, as well ...",
      htmlSnippet:
        "Feb 18, 2021 <b>...</b> Learn the basics of <b>testing</b> your Android Kotlin apps. In this codelab you&#39;ll learn to <br>\nrun <b>tests</b>, write basic <b>tests</b>, work with AndroidX <b>Test</b>, as well&nbsp;...",
      cacheId: "muAx0jnXLYUJ",
      formattedUrl:
        "https://codelabs.developers.google.com/.../advanced-android-kotlin-training- testing-basics/",
      htmlFormattedUrl:
        "https://codelabs.developers.google.com/.../advanced-android-kotlin-training- <b>testing</b>-basics/",
      pagemap: {
        cse_thumbnail: [
          {
            src:
              "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTIiyuDULJELWS4EckDT_NkpCNM8Q6P_8ye5QbltHzulEvkPJbJPmpxmHzl",
            width: "299",
            height: "168",
          },
        ],
        metatags: [
          {
            "og:image":
              "https://developer.android.com/images/social/android-developers.png",
            "og:type": "website",
            "theme-color": "#3ddc84",
            "og:image:width": "1200",
            "twitter:card": "summary_large_image",
            "google-signin-client-id":
              "721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com",
            "og:site_name": "Android Developers",
            "og:title":
              "Advanced Android in Kotlin 05.1: Testing Basics  |  Android Developers",
            "og:image:height": "675",
            "og:description":
              "Learn the basics of testing your Android Kotlin apps. In this codelab you’ll learn to run tests, write basic tests, work with AndroidX Test, as well as test ViewModel and LiveData.",
            original_source: "https://docs.google.com/document/d//edit",
            viewport: "width=device-width, initial-scale=1",
            "og:locale": "en",
            "google-signin-scope":
              "profile email https://www.googleapis.com/auth/developerprofiles https://www.googleapis.com/auth/developerprofiles.award",
            "og:url":
              "https://developer.android.com/codelabs/advanced-android-kotlin-training-testing-basics",
          },
        ],
        cse_image: [
          {
            src:
              "https://developer.android.com/images/social/android-developers.png",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title:
        "Kroger begins testing drone deliveries for baby products and s ...",
      htmlTitle:
        "Kroger begins <b>testing</b> drone deliveries for baby products and s ...",
      link:
        "https://news.google.com/__i/rss/rd/articles/CBMiTmh0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS8yMDIxLzUvMy8yMjQxNjk1Ny9rcm9nZXItZHJvbmUtZXhwcmVzcy1ncm9jZXJpZXMtb2hpb9IBW2h0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS9wbGF0Zm9ybS9hbXAvMjAyMS81LzMvMjI0MTY5NTcva3JvZ2VyLWRyb25lLWV4cHJlc3MtZ3JvY2VyaWVzLW9oaW8?oc=5",
      displayLink: "news.google.com",
      snippet:
        "12 hours ago ... Kroge is partnering with Drone Express to deliver groceries weighing up to about \nfive pounds from a pilot store in Centerville, Ohio. The Kroger ...",
      htmlSnippet:
        "12 hours ago <b>...</b> Kroge is partnering with Drone Express to deliver groceries weighing up to about <br>\nfive pounds from a pilot store in Centerville, Ohio. The Kroger&nbsp;...",
      cacheId: "Lh2vtc-AsnEJ",
      formattedUrl:
        "https://news.google.com/__.../ CBMiTmh0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS8yMDIxLzUvMy8yMj...",
      htmlFormattedUrl:
        "https://news.google.com/__.../ CBMiTmh0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS8yMDIxLzUvMy8yMj...",
      pagemap: {
        cse_thumbnail: [
          {
            src:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSimnj_GyhZIrPDQeiOqTcIBic4naDLsjy50_Euku8_hK8lGAFqn3tTCUc",
            width: "311",
            height: "162",
          },
        ],
        metatags: [
          {
            "og:image":
              "https://cdn.vox-cdn.com/thumbor/0vQHrmRZk44MbMRFxCjnnRrsWIQ=/0x111:2000x1158/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/22487785/Kroger_Delivery_x_Drone_Express_04.jpg",
            "article:published_time": "2021-05-03T07:32:17-04:00",
            "og:image:width": "1200",
            "twitter:card": "summary_large_image",
            "og:site_name": "The Verge",
            "sailthru.tags": "general,the-verge,front-page,tech,drone,news",
            "twitter:url":
              "https://www.theverge.com/2021/5/3/22416957/kroger-drone-express-groceries-ohio",
            "apple-mobile-web-app-title": "Verge",
            "parsely-author": "Thomas Ricker",
            "msapplication-tileimage":
              "https://cdn.vox-cdn.com/uploads/chorus_asset/file/7396113/221a67c8-a10f-11e6-8fae-983107008690.0.png",
            "og:description":
              "Partnering with Drone Express in Ohio, then California",
            "article:publisher": "http://www.facebook.com/verge",
            "twitter:image":
              "https://cdn.vox-cdn.com/thumbor/anX9MI9L7Ax1Je6SqcX8oJYS2No=/0x134:2000x1134/fit-in/1200x600/cdn.vox-cdn.com/uploads/chorus_asset/file/22487785/Kroger_Delivery_x_Drone_Express_04.jpg",
            "ahrefs-site-verification":
              "1e57a609922037a3fbdc1c22efd7334113f174f15608f37e1b8538a7b4ce64c3",
            "parsely-type": "post",
            "twitter:site": "verge",
            "article:modified_time": "2021-05-03T07:32:17-04:00",
            "parsely-link":
              "https://www.theverge.com/2021/5/3/22416957/kroger-drone-express-groceries-ohio",
            "sailthru.title":
              "Kroger begins testing drone deliveries for baby products and s’mores",
            "parsely-image-url":
              "https://cdn.vox-cdn.com/thumbor/Ut1evRh2oePu3aL_dNu0Tcc2M8w=/0x72:2000x1197/1600x900/cdn.vox-cdn.com/uploads/chorus_image/image/69226543/Kroger_Delivery_x_Drone_Express_04.0.jpg",
            "parsely-section": "front-page",
            "msapplication-tilecolor": "#393092",
            "sailthru.date": "2021-05-03T07:32:17-04:00",
            "og:type": "article",
            "twitter:title":
              "Kroger begins testing drone deliveries for baby products and s’mores",
            "msvalidate.01": "D385D0326A3AE144205C298DB34B4E94",
            author: "Thomas Ricker",
            "og:title":
              "Kroger begins testing drone deliveries for baby products and s’mores",
            "og:image:height": "630",
            "sailthru.image.thumb":
              "https://cdn.vox-cdn.com/thumbor/mzPEk3MOiO-UgFG1qviqWImJjsI=/367x0:1634x1267/200x200/cdn.vox-cdn.com/uploads/chorus_image/image/69226543/Kroger_Delivery_x_Drone_Express_04.0.jpg",
            "parsely-title":
              "Kroger begins testing drone deliveries for baby products and s’mores",
            "article:author": "https://www.facebook.com/thomas.ricker",
            "style-tools":
              "https://www.theverge.com/style/community/372/32334988fadd8335f2fc5857fb5172c0/tools.css",
            "parsely-pub-date": "2021-05-03T07:32:17-04:00",
            "fb:app_id": "549923288395304",
            "sailthru.description":
              'Kroge is partnering with Drone Express to deliver groceries weighing up to about five pounds from a pilot store in Centerville, Ohio. The Kroger Drone Delivery service says that groceries will be flown by "certified drone pilots under FAA approval."',
            "parsely-tags": "verge,front-page,tech,drone,news",
            outbrainsection: "news",
            viewport: "width=device-width, initial-scale=1, shrink-to-fit=no",
            "twitter:description":
              "Partnering with Drone Express in Ohio, then California",
            "og:url":
              "https://www.theverge.com/2021/5/3/22416957/kroger-drone-express-groceries-ohio",
            "sailthru.image.full":
              "https://cdn.vox-cdn.com/thumbor/Ut1evRh2oePu3aL_dNu0Tcc2M8w=/0x72:2000x1197/1600x900/cdn.vox-cdn.com/uploads/chorus_image/image/69226543/Kroger_Delivery_x_Drone_Express_04.0.jpg",
          },
        ],
        cse_image: [
          {
            src:
              "https://cdn.vox-cdn.com/thumbor/0vQHrmRZk44MbMRFxCjnnRrsWIQ=/0x111:2000x1158/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/22487785/Kroger_Delivery_x_Drone_Express_04.jpg",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Genetic Testing Fact Sheet - National Cancer Institute",
      htmlTitle:
        "Genetic <b>Testing</b> Fact Sheet - National Cancer Institute",
      link:
        "http://feedproxy.google.com/~r/ncifactsheets/~3/nlZ_7MZvBxY/genetic-testing-fact-sheet",
      displayLink: "feedproxy.google.com",
      snippet:
        "Mar 15, 2019 ... A fact sheet about genetic testing for inherited cancer risk. Includes who should \nconsider testing, and how to understand test results.",
      htmlSnippet:
        "Mar 15, 2019 <b>...</b> A fact sheet about genetic <b>testing</b> for inherited cancer risk. Includes who should <br>\nconsider <b>testing</b>, and how to understand <b>test</b> results.",
      cacheId: "-NmfdsHV-mUJ",
      formattedUrl:
        "feedproxy.google.com/~r/ncifactsheets/~3/nlZ.../genetic-testing-fact-sheet",
      htmlFormattedUrl:
        "feedproxy.google.com/~r/ncifactsheets/~3/nlZ.../genetic-<b>testing</b>-fact-sheet",
      pagemap: {
        cse_thumbnail: [
          {
            src:
              "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRv9_IsCRoWZ1nanhRSbtudSNe1fGFmTGUsEdRpwhR__sd2CpA7VmdEuK4p",
            width: "310",
            height: "163",
          },
        ],
        question: [
          {
            name: "What is genetic testing?",
          },
          {
            name:
              "Does someone who inherits a cancer susceptibility variant always get cancer?",
          },
          {
            name:
              "What genetic tests are available for cancer risk assessment?",
          },
          {
            name: "Who should consider genetic testing for cancer risk?",
          },
          {
            name:
              "What is the role of genetic counseling in genetic testing for a hereditary cancer syndrome?",
          },
          {
            name: "How is genetic testing done?",
          },
          {
            name: "What do the results of genetic testing mean?",
          },
          {
            name: "Who has access to a person’s genetic test results?",
          },
          {
            name:
              "Can at-home or direct-to-consumer genetic tests be used to test for cancer risk?",
          },
          {
            name:
              "What are some of the benefits of genetic testing for inherited cancer susceptibility syndromes?",
          },
          {
            name:
              "What are some of the possible harms of genetic testing for inherited cancer susceptibility syndromes?",
          },
          {
            name: "How are genetic tests regulated?",
          },
          {
            name:
              "What research is being done to improve genetic testing for cancer?",
          },
        ],
        answer: [
          {
            text:
              "Genetic testing looks for specific inherited changes (variants) in a person’s genes. Genetic variants can have harmful, beneficial, neutral (no effect), or unknown or uncertain effects on...",
          },
          {
            text:
              "No. Even if a cancer susceptibility variant is present in a family, it does not necessarily mean that everyone who inherits the variant will develop cancer. Several factors influence whether...",
          },
          {
            text:
              "More than 50 hereditary cancer syndromes have been described; see the PDQ Cancer Genetics Overview for a list of familial cancer susceptibility syndromes. Most of these are caused by harmful...",
          },
          {
            text:
              "People who are concerned about whether their family history puts them at risk for cancer should consult with a genetic counselor. The features of a person’s personal or family medical history...",
          },
          {
            text:
              "Genetic counseling is generally recommended before any genetic testing for a hereditary cancer syndrome and may also be performed after the test, especially if a positive result is found and...",
          },
          {
            text:
              "Genetic tests are usually requested by a person’s genetic counselor, doctor, or other health care provider who has reviewed the individual’s person and family history. The genetic test...",
          },
          {
            text:
              "Genetic testing can give several possible results: positive, negative, true negative, uninformative negative, variant of uncertain significance, or benign (harmless) variant. Positive result....",
          },
          {
            text:
              "Medical test results are normally included in a person’s medical records, particularly if a doctor or other health care provider has ordered the test or has been consulted about the test...",
          },
          {
            text:
              "An increasing number of companies offer at-home genetic testing, also known as direct-to-consumer (DTC) genetic testing. People collect a saliva sample or a mouth swab themselves and submit...",
          },
          {
            text:
              "There can be benefits to genetic testing, regardless of whether a person receives a positive or a negative result. An informative negative test can provide the person with peace of mind that...",
          },
          {
            text:
              "Genetic testing can have potential emotional, social, and financial harms, including: Psychological stress of learning that one has a genetic variant that increases cancer risk and having to...",
          },
          {
            text:
              "U.S. laboratories that perform health-related testing, including genetic testing, are regulated under the Clinical Laboratory Improvement Amendments (CLIA) program. Laboratories that are certified...",
          },
          {
            text:
              "Research is ongoing to find better ways to detect, treat, and prevent cancer in people who carry genetic variants that increase the risk of certain cancers. Scientists are also doing studies...",
          },
        ],
        metatags: [
          {
            "application-name": "Cancer.gov",
            "og:image":
              "https://www.cancer.gov/sites/g/files/xnrzdm211/files/cgov_image/social_media/100/100/3/files/nhgri-genetic-testing-social-media.jpg",
            "msapplication-config":
              "/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/browserconfig.xml?v=1",
            "twitter:card": "summary",
            "og:type": "Website",
            "og:site_name": "National Cancer Institute",
            "dcterms.ispartof": "Causes and Prevention",
            handheldfriendly: "true",
            "dcterms.type": "cgvArticle",
            "og:title": "Genetic Testing Fact Sheet",
            "apple-mobile-web-app-title": "Cancer.gov",
            "dcterms.subject": "About Cancer",
            "og:description":
              "A fact sheet about genetic testing for inherited cancer risk. Includes who should consider testing, and how to understand test results.",
            "dcterms.issued": "04/26/2019 - 08:00",
            "dcterms.isreferencedby": "event1",
            viewport:
              "width=device-width, user-scalable=yes, initial-scale=1, minimum-scale=1",
            mobileoptimized: "width",
            "og:url":
              "https://www.cancer.gov/about-cancer/causes-prevention/genetics/genetic-testing-fact-sheet",
            "dcterms.coverage": "nciglobal,ncienterprise",
          },
        ],
        cse_image: [
          {
            src:
              "https://www.cancer.gov/sites/g/files/xnrzdm211/files/cgov_image/social_media/100/100/3/files/nhgri-genetic-testing-social-media.jpg",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "How Google's Algorithm is Focused on Its Users - Google Search",
      htmlTitle:
        "How Google&#39;s Algorithm is Focused on Its Users - Google Search",
      link: "https://www.google.com/search/howsearchworks/mission/users/",
      displayLink: "www.google.com",
      snippet:
        "Learn how changes to Google's algorithm are tested with Google search ... We \nput all possible changes to Search through rigorous testing and evaluation.",
      htmlSnippet:
        "Learn how changes to Google&#39;s algorithm are <b>tested</b> with Google search ... We <br>\nput all possible changes to Search through rigorous <b>testing</b> and evaluation.",
      cacheId: "ObxN5sVIizUJ",
      formattedUrl:
        "https://www.google.com/search/howsearchworks/mission/users/",
      htmlFormattedUrl:
        "https://www.google.com/search/howsearchworks/mission/users/",
      pagemap: {
        metatags: [
          {
            referrer: "no-referrer",
            "twitter:title":
              "How Google's Algorithm is Focused on Its Users - Google Search",
            viewport: "width=device-width, initial-scale=1.0",
            "twitter:description":
              "Learn how changes to Google's algorithm are tested with Google search experiments to ensure that we continue to provide the most useful results, and how ads help us keep Google Search free.",
            "og:title":
              "How Google's Algorithm is Focused on Its Users - Google Search",
            "og:description":
              "Learn how changes to Google's algorithm are tested with Google search experiments to ensure that we continue to provide the most useful results, and how ads help us keep Google Search free.",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title:
        "Testing face masks: Lab tests reveal the safest and most effective ...",
      htmlTitle:
        "<b>Testing</b> face masks: Lab <b>tests</b> reveal the safest and most effective ...",
      link:
        "https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9RUhWeXkwOEwyZ03SAQA?oc=5",
      displayLink: "news.google.com",
      snippet:
        "Nov 13, 2020 ... How effective are your face masks? Months into the coronavirus pandemic there \nare still no standards or regulations for consumer masks.",
      htmlSnippet:
        "Nov 13, 2020 <b>...</b> How effective are your face masks? Months into the coronavirus pandemic there <br>\nare still no standards or regulations for consumer masks.",
      formattedUrl:
        "https://news.google.com/__.../ CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9RUhWe...",
      htmlFormattedUrl:
        "https://news.google.com/__.../ CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9RUhWe...",
      pagemap: {
        cse_thumbnail: [
          {
            src:
              "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS5PNhyeFe-bq-6AQ1pojwvlDU_LFDFXemAn3FDYgXyAUHREds7_5MWSPJu",
            width: "300",
            height: "168",
          },
        ],
        imageobject: [
          {
            width: "1280",
            url: "https://i.ytimg.com/vi/EHVyy08L2gM/maxresdefault.jpg",
            height: "720",
          },
        ],
        person: [
          {
            name: "CBC News",
            url: "http://www.youtube.com/user/cbcnews",
          },
        ],
        metatags: [
          {
            "og:image": "https://i.ytimg.com/vi/EHVyy08L2gM/maxresdefault.jpg",
            "theme-color": "rgba(255,255,255,0.98)",
            "og:image:width": "1280",
            "twitter:card": "player",
            "og:site_name": "YouTube",
            "twitter:url": "https://www.youtube.com/watch?v=EHVyy08L2gM",
            "al:android:package": "com.google.android.youtube",
            title:
              "Testing face masks: Lab tests reveal the safest and most effective (Marketplace)",
            "al:ios:url":
              "vnd.youtube://www.youtube.com/watch?v=EHVyy08L2gM&feature=applinks",
            "og:description":
              "How effective are your face masks? Months into the coronavirus pandemic there are still no standards or regulations for consumer masks. So we asked the Unive...",
            "al:ios:app_store_id": "544007664",
            "twitter:site": "@youtube",
            "og:video:type": "text/html",
            "og:video:height": "720",
            "og:video:url": "https://www.youtube.com/embed/EHVyy08L2gM",
            "og:type": "video.other",
            "al:ios:app_name": "YouTube",
            "og:title":
              "Testing face masks: Lab tests reveal the safest and most effective (Marketplace)",
            "og:image:height": "720",
            "al:web:url":
              "http://www.youtube.com/watch?v=EHVyy08L2gM&feature=applinks",
            "og:video:secure_url": "https://www.youtube.com/embed/EHVyy08L2gM",
            "og:video:tag": "Canada",
            "og:video:width": "1280",
            "al:android:url":
              "vnd.youtube://www.youtube.com/watch?v=EHVyy08L2gM&feature=applinks",
            "fb:app_id": "87741124305",
            "og:url": "https://www.youtube.com/watch?v=EHVyy08L2gM",
            "al:android:app_name": "YouTube",
          },
        ],
        videoobject: [
          {
            embedurl: "https://www.youtube.com/embed/EHVyy08L2gM",
            playertype: "HTML5 Flash",
            isfamilyfriendly: "true",
            uploaddate: "2020-11-13",
            description:
              "How effective are your face masks? Months into the coronavirus pandemic there are still no standards or regulations for consumer masks. So we asked the Unive...",
            videoid: "EHVyy08L2gM",
            url: "https://www.youtube.com/watch?v=EHVyy08L2gM",
            duration: "PT7M42S",
            unlisted: "False",
            name:
              "Testing face masks: Lab tests reveal the safest and most effective (Marketplace)",
            paid: "False",
            width: "1280",
            regionsallowed:
              "AD,AE,AF,AG,AI,AL,AM,AO,AQ,AR,AS,AT,AU,AW,AX,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BL,BM,BN,BO,BQ,BR,BS,BT,BV,BW,BY,BZ,CA,CC,CD,CF,CG,CH,CI,CK,CL,CM,CN,CO,CR,CU,CV,CW,CX,CY,CZ,DE,DJ,DK,DM,DO,DZ,EC,EE,EG,EH...",
            genre: "News & Politics",
            interactioncount: "1420385",
            channelid: "UCuFFtHWoLl5fauMMD5Ww2jA",
            datepublished: "2020-11-13",
            thumbnailurl:
              "https://i.ytimg.com/vi/EHVyy08L2gM/maxresdefault.jpg",
            height: "720",
          },
        ],
        cse_image: [
          {
            src: "https://i.ytimg.com/vi/EHVyy08L2gM/maxresdefault.jpg",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title:
        "The mathematical strategy that could transform coronavirus testing",
      htmlTitle:
        "The mathematical strategy that could transform coronavirus <b>testing</b>",
      link:
        "https://news.google.com/__i/rss/rd/articles/CBMiMmh0dHBzOi8vd3d3Lm5hdHVyZS5jb20vYXJ0aWNsZXMvZDQxNTg2LTAyMC0wMjA1My020gEA?oc=5",
      displayLink: "news.google.com",
      snippet:
        "Jul 10, 2020 ... Groups of samples that test negative are ruled out. But if a group tests positive, \nevery sample in that group is then retested individually.",
      htmlSnippet:
        "Jul 10, 2020 <b>...</b> Groups of samples that <b>test</b> negative are ruled out. But if a group <b>tests</b> positive, <br>\nevery sample in that group is then retested individually.",
      formattedUrl:
        "https://news.google.com/__.../ CBMiMmh0dHBzOi8vd3d3Lm5hdHVyZS5jb20vYXJ0aWNsZXMvZDQx...",
      htmlFormattedUrl:
        "https://news.google.com/__.../ CBMiMmh0dHBzOi8vd3d3Lm5hdHVyZS5jb20vYXJ0aWNsZXMvZDQx...",
      pagemap: {
        cse_thumbnail: [
          {
            src:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl1ZTgEZODihtOSLOZGy4xDzTIqZtrOWIjH5_8WTzWdZDtViDLblU2pDo",
            width: "300",
            height: "168",
          },
        ],
        organization: [
          {
            name: "Macmillan Publishers Limited, part of Springer Nature",
          },
          {
            name: "Nature Editorial",
          },
        ],
        periodical: [
          {
            publisher: "Springer Nature",
          },
        ],
        metatags: [
          {
            "dc.publisher": "Nature Publishing Group",
            "og:image":
              "https://media.nature.com/lw1024/magazine-assets/d41586-020-02053-6/d41586-020-02053-6_18161284.jpg",
            "prism.startingpage": "504",
            "msapplication-config": "/static/browserconfig.e35b3b052c.xml",
            "twitter:card": "summary_large_image",
            "theme-color": "#000000",
            "dc.format": "text/html",
            "dc.rights":
              "©2021 Macmillan Publishers Limited. All Rights Reserved.",
            "prism.publicationdate": "2020-07-10",
            "og:description":
              "Four charts show how pooling samples from many people can save time or resources.",
            "prism.rightsagent": "journalpermissions@springernature.com",
            "twitter:image":
              "https://media.nature.com/lw1024/magazine-assets/d41586-020-02053-6/d41586-020-02053-6_18161284.jpg",
            "wt.z_cg_type": "News",
            "prism.number": "7817",
            "twitter:site": "@nature",
            "dc.source": "Nature 2021 583:7817",
            "dc.type": "News",
            "dc.rightsagent": "journalpermissions@springernature.com",
            "dc.copyright": "2021 Nature",
            "dc.creator": "Smriti Mallapaty",
            journal_id: "41586",
            "msapplication-tilecolor": "#000000",
            "application-name": "Nature",
            "prism.publicationname": "Nature",
            "og:type": "article",
            "twitter:title":
              "The mathematical strategy that could transform coronavirus testing",
            "dc.description":
              "Four charts show how pooling samples from many people can save time or resources.  Four charts show how pooling samples from many people can save time or resources.",
            "wt.z_subject_term": "Technology, Infection, Virology",
            "wt.page_categorisation": "Article page",
            "og:title":
              "The mathematical strategy that could transform coronavirus testing",
            "wt.cg_s": "News",
            "prism.doi": "doi:10.1038/d41586-020-02053-6",
            "wt.cg_n": "Nature",
            "dc.date": "2020-07-10",
            "prism.endingpage": "505",
            "prism.volume": "583",
            viewport: "width=device-width, initial-scale=1.0, shrink-to-fit=no",
            "twitter:description":
              "Four charts show how pooling samples from many people can save time or resources.",
            "wt.template": "oscar",
            "dc.title":
              "The mathematical strategy that could transform coronavirus testing",
            "prism.section": "News",
            "prism.url": "https://www.nature.com/articles/d41586-020-02053-6",
            "dc.identifier": "doi:10.1038/d41586-020-02053-6",
            "dc.subject": "Infection",
            "og:url": "https://www.nature.com/articles/d41586-020-02053-6",
            "dc.language": "En",
            "prism.copyright": "2021 Nature",
            doi: "10.1038/d41586-020-02053-6",
          },
        ],
        cse_image: [
          {
            src:
              "https://media.nature.com/lw1024/magazine-assets/d41586-020-02053-6/d41586-020-02053-6_18161284.jpg",
          },
        ],
        newsarticle: [
          {
            articlebody:
              "NEWS 10 July 2020 The mathematical strategy that could transform coronavirus testing Four charts show how pooling samples from many people can save time or resources. Smriti Mallapaty Smriti...",
            headline:
              "The mathematical strategy that could transform coronavirus testing",
            datepublished: "10 July 2020",
          },
        ],
        listitem: [
          {
            item: "nature",
            name: "nature",
          },
          {
            item: "news",
            name: "news",
          },
          {
            item: "article",
            name: "article",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Google Is Testing Its Controversial New Ad Targeting Tech in ...",
      htmlTitle:
        "Google Is <b>Testing</b> Its Controversial New Ad Targeting Tech in ...",
      link:
        "https://news.google.com/__i/rss/rd/articles/CBMidGh0dHBzOi8vd3d3LmVmZi5vcmcvZGVlcGxpbmtzLzIwMjEvMDMvZ29vZ2xlLXRlc3RpbmctaXRzLWNvbnRyb3ZlcnNpYWwtbmV3LWFkLXRhcmdldGluZy10ZWNoLW1pbGxpb25zLWJyb3dzZXJzLWhlcmVz0gEA?oc=5",
      displayLink: "news.google.com",
      snippet:
        "Mar 30, 2021 ... Google Is Testing Its Controversial New Ad Targeting Tech in Millions of \nBrowsers. Here's What We Know. DEEPLINKS BLOG. By Bennett ...",
      htmlSnippet:
        "Mar 30, 2021 <b>...</b> Google Is <b>Testing</b> Its Controversial New Ad Targeting Tech in Millions of <br>\nBrowsers. Here&#39;s What We Know. DEEPLINKS BLOG. By Bennett&nbsp;...",
      cacheId: "ohDVM5lap84J",
      formattedUrl:
        "https://news.google.com/__.../ CBMidGh0dHBzOi8vd3d3LmVmZi5vcmcvZGVlcGxpbmtzLzIwMjEvMD...",
      htmlFormattedUrl:
        "https://news.google.com/__.../ CBMidGh0dHBzOi8vd3d3LmVmZi5vcmcvZGVlcGxpbmtzLzIwMjEvMD...",
      pagemap: {
        cse_thumbnail: [
          {
            src:
              "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSiI7N20r3B-f-neTIvcMy7QxfAb0PntvocdQ4Z3EUA7z4xZsDN9wRTv-tg",
            width: "318",
            height: "159",
          },
        ],
        metatags: [
          {
            "og:image":
              "https://www.eff.org/files/banner_library/floc-animation-1200.gif",
            "og:image:width": "1200",
            "twitter:card": "summary_large_image",
            "article:published_time": "2021-03-30T20:35:38-07:00",
            "og:site_name": "Electronic Frontier Foundation",
            "twitter:image:height": "600",
            "og:image:type": "image/gif",
            "og:description":
              "Update, April 9, 2021 : We've launched Am I FLoCed, a new site that will tell you whether your Chrome browser has been turned into a guinea pig for Federated Learning of Cohorts or FLoC, Google’s latest targeted advertising experiment. Today, Google launched an “origin trial” of Federated Learning...",
            "og:image:secure_url":
              "https://www.eff.org/files/banner_library/floc-animation-1200.gif",
            "twitter:image":
              "https://www.eff.org/files/banner_library/floc-animation-1200.gif",
            "article:publisher": "https://www.facebook.com/eff",
            "twitter:site": "@eff",
            "twitter:image:width": "1200",
            "article:modified_time": "2021-04-09T14:02:41-07:00",
            "og:type": "article",
            "twitter:title":
              "Google Is Testing Its Controversial New Ad Targeting Tech in Millions",
            handheldfriendly: "true",
            "og:image:url":
              "https://www.eff.org/files/banner_library/floc-animation-1200.gif",
            author: "Bennett Cyphers",
            "og:title":
              "Google Is Testing Its Controversial New Ad Targeting Tech in Millions of Browsers. Here’s What We Know.",
            "og:image:height": "600",
            "og:updated_time": "2021-04-09T14:02:41-07:00",
            viewport: "width=device-width",
            "twitter:description":
              "Update, April 9, 2021 : We've launched Am I FLoCed, a new site that will tell you whether your Chrome browser has been turned into a guinea pig for Federated Learning of Cohorts or FLoC, Google’s",
            mobileoptimized: "width",
            "og:url":
              "https://www.eff.org/deeplinks/2021/03/google-testing-its-controversial-new-ad-targeting-tech-millions-browsers-heres",
          },
        ],
        cse_image: [
          {
            src:
              "https://www.eff.org/files/banner_library/floc-animation-1200.gif",
          },
        ],
      },
    },
  ],
};
